[package]
name = "migrat"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
slint = "1.11.0"
tokio = { version = "1.45.1", features = ["full"] }

[build-dependencies]
slint-build = "1.8.0"
