import { Button, HorizontalBox, TextEdit, VerticalBox } from "std-widgets.slint";
import { HomePage } from "views/HomePage.slint";
import { SettingsPage } from "views/SettingsPage.slint";

export component AppWindow inherits Window {
    title: "Migrat";
    icon: @image-url("public/icon.png");
    preferred-width: 1000px;
    preferred-height: 750px;
    padding: 10px;
    default-font-size: 14px;
    default-font-family: "Arial";
    in-out property <string> current_page: "home";
            // Vista condicional
    HomePage {
        visible: root.current_page == "home";
        navigate_to_settings => {
            root.current_page = "settings";
        }
    }

    SettingsPage {
        visible: root.current_page == "settings";
        navigate_to_home => {
            root.current_page = "home";
        }
    }
}
